// <auto-generated />
using System;
using BTL_Tu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BTL_Tu.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BTL_Tu.Models.HoSo", b =>
                {
                    b.Property<int>("MaSoHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HocSinhMaSoHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("MaSoHocSinh")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSoHoSo");

                    b.HasIndex("HocSinhMaSoHocSinh");

                    b.ToTable("HoSos");
                });

            modelBuilder.Entity("BTL_Tu.Models.HocSinh", b =>
                {
                    b.Property<int>("MaSoHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaSoPhuHuynh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PhuHuynhMaSoPhuHuynh")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSoHocSinh");

                    b.HasIndex("PhuHuynhMaSoPhuHuynh");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("BTL_Tu.Models.PhuHuynh", b =>
                {
                    b.Property<int>("MaSoPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSoPhuHuynh");

                    b.ToTable("PhuHuynhs");
                });

            modelBuilder.Entity("BTL_Tu.Models.HoSo", b =>
                {
                    b.HasOne("BTL_Tu.Models.HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("HocSinhMaSoHocSinh");
                });

            modelBuilder.Entity("BTL_Tu.Models.HocSinh", b =>
                {
                    b.HasOne("BTL_Tu.Models.PhuHuynh", "PhuHuynh")
                        .WithMany("HocSinhs")
                        .HasForeignKey("PhuHuynhMaSoPhuHuynh");
                });
#pragma warning restore 612, 618
        }
    }
}
